# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [mai1n]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      - name: Build Docker Image
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'ccr.ccs.tencentyun.com'
          namespaces: 'ibule'
          repository_name: 'vue3'
          user_name: ${{ secrets.TX_ACCESS_KEY_ID }}
          password: ${{ secrets.TX_SECRET_ACCESS_KEY }}
          image_version: 'latest'
          docker_file: '.'
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
      # # 打包镜像推送到阿里云容器镜像服务
      # - name: Build the Docker image
      #   run: |
      #     sudo docker login --username=100014644489  ccr.ccs.tencentyun.com
      #     docker build -t vue3:latest .
      #     sudo docker tag vue3 ccr.ccs.tencentyun.com/ibule/vue3:latest
      #     sudo docker push ccr.ccs.tencentyun.com/ibule/vue3:latest
      # - name: ssh docker login # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }} 
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     script: cd ~ && sh bilibili-vue-deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}   