name: node # Actions名称
on:
push:
# 只有master分支发生push事件时，才会触发workflow
branches: [ main ]
jobs:

# 这里我使用的是yarn，想用npm的同学将yarn命令修改为npm命令即可
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '14'
- run: npm install
# 打包
- name: build project
run: npm run build