# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      - name: Build Docker Image
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'ccr.ccs.tencentyun.com'
          namespaces: 'ibule'
          repository_name: 'vue3'
          user_name: ${{ secrets.TX_ACCESS_KEY_ID }}
          password: ${{ secrets.TX_SECRET_ACCESS_KEY }}
          image_version: 'latest'
          docker_file: '.'
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
  pull-docker:
    needs: [ build ]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TX_HOST }}
          username: ${{ secrets.TX_HOST_USERNAME }}
          password: ${{ secrets.TX_HOST_PASSWORD }}
          script: |
            docker stop $(docker ps --filter ancestor=${{ secrets.REGISTRY }} -q) 2>&1
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.REGISTRY }} -q) 2>&1
            docker pull ccr.ccs.tencentyun.com/ibule/${{ secrets.REGISTRY }}:latest
            docker run --name ${{ secrets.REGISTRY }} -d -p 8080:8080 ccr.ccs.tencentyun.com/ibule/${{ secrets.REGISTRY }}:latest